machin = ["The new Marvel movie is breaking box office records.",
    "The Grammy Awards are a celebration of the best music of the year.",
    "The latest season of Game of Thrones had fans on the edge of their seats.",
    "The rise of streaming services is transforming the entertainment industry.",
    "The role of social media in promoting films and shows is growing.",
    "The popularity of podcasts is creating new storytelling formats.",
    "The evolution of animation technology is enhancing visual storytelling.",
    "The impact of fan culture on franchises is significant.",
    "The use of CGI in movies is creating stunning visual effects.",
    "The role of video games in entertainment is expanding globally.",
    "The rise of independent films is bringing diverse stories to audiences.",
    "The importance of representation in media is being emphasized.",
    "The popularity of live concerts is bringing fans closer to artists.",
    "The growth of esports is attracting massive audiences worldwide.",
    "The role of documentaries in raising awareness is widely recognized.",
    "The influence of nostalgia in entertainment is shaping content creation.",
    "The impact of award shows on the careers of artists is notable.",
    "The evolution of theme parks is enhancing visitor experiences.",
    "The role of influencers in shaping entertainment trends is growing.",
    "The rise of interactive storytelling is engaging audiences in new ways.",
    "The popularity of true crime shows is captivating viewers.",
    "The role of music streaming platforms in promoting artists is significant.",
    "The impact of remakes and reboots on classic franchises is debated.",
    "The evolution of sound design is enhancing cinematic experiences.",
    "The role of fan theories in keeping franchises alive is notable.",
    "The rise of virtual concerts is redefining live performances.",
    "The importance of diversity in casting is gaining attention.",
    "The growth of international cinema is bringing global stories to light.",
    "The use of AI in creating music and art is sparking innovation.",
    "The impact of binge-watching culture on content consumption is profound.",
    "The role of festivals in celebrating creative arts is widely acknowledged.",
    "The rise of audiobooks is creating new ways to enjoy literature.",
    "The influence of fashion in entertainment is shaping trends.",
    "The popularity of reality TV shows is engaging diverse audiences.",
    "The role of fan conventions in connecting creators and fans is significant.",
    "The use of motion capture in acting is transforming performances.",
    "The impact of streaming platforms on traditional TV networks is notable.",
    "The evolution of home theater systems is enhancing entertainment at home.",
    "The role of nostalgia in reviving classic TV shows is undeniable."]

print(len(machin))